### ISSUE TITLE
Initial setup with React, Vite, ShadCN, and React Icons in `frontend`

### ISSUE THREAD

**Issue by emmanuelAkpe** [mestafrica/digitizing-the-ges-curriculum#1]
## Description

This issue is to set up the initial frontend project structure in the `frontend` directory using the following technologies:
- React
- Vite
- Tailwind Css
- ShadCN (Shad Components with Tailwind CSS pre-configured)
- React Icons

## Tasks

1. **Initialize the Project in `frontend`:**
   - Navigate to the `frontend` directory.
   - Create a new Vite project with React template.
   - Set up project structure.

2. **Install Dependencies:**
   -  Install Tailwind CSS and its peer dependencies.
   - Install ShadCN
   - Install React Icons.

3. **Set Up ShadCN:**
   - Integrate ShadCN components.

4. **Integrate React Icons:**
   - Install and configure React Icons.
   - Add sample icons to a component to verify the setup.

## Acceptance Criteria

- The project should be initialized with Vite and React in the `frontend` directory.
- ShadCN components should be integrated and tested with a button.
- React Icons should be installed and a sample icon should be displayed.

## Steps to Reproduce

1. Clone the repository.
2. Navigate to the `frontend` directory.
3. Follow the steps to set up the project.
4. Run the development server and verify the setup.

## Additional Context

- [Vite Documentation](https://vitejs.dev/guide/)
- [ShadCN Documentation](https://ui.shadcn.com/docs/installation/vite)
- [React Icons Documentation](https://react-icons.github.io/react-icons/)

**Comment by iamatinad** [comment]
@emmanuelAkpe please I would like to pick up this issue

**Comment by iamatinad** [comment]
@emmanuelAkpe please are we ommiting tailwind?

**Comment by emmanuelAkpe** [comment]
Thank you for volunteering to pick up this issue, @iamatinad . Please proceed and let me know if you encounter any challenges.
