### ISSUE TITLE
Hero section and the partner sections

### ISSUE THREAD

**Issue by emmanuelAkpe** [mestafrica/digitizing-the-ges-curriculum#11]
## Description
This issue involves building the Hero section and the partner sections of the landing pages based on the  provided Figma design(https://www.figma.com/design/f6ysqYxUe3PWsDMGKWDtDQ/Digitizing-the-GES-Curriculum-Figma?node-id=0-1&t=1fnNqqJdv6WRWMXV-1) inside the `frontend`

<img width="510" alt="Screen Shot 2024-08-01 at 4 14 35 PM" src="https://github.com/user-attachments/assets/00ea2aca-d780-4127-ba07-111fad992a67">

## Tasks

1. **Set up a component to contain the hero and partner sections**

2. **Test the Implementation**
   - Verify that  both sections are responsive across various devices,also ensuring that it matches the figma design.

## Acceptance Criteria
-matches the design
- responsive across various devices

**Comment by iamatinad** [comment]
@emmanuelAkpe  please I'd like to pick this up

**Comment by emmanuelAkpe** [comment]
Thank you. Will kindly assign to you
