### ISSUE TITLE
Building the features sections

### ISSUE THREAD

**Issue by emmanuelAkpe** [mestafrica/digitizing-the-ges-curriculum#13]
## Description
This issue involves building the  sections  in the image below based on the  provided Figma design(https://www.figma.com/design/f6ysqYxUe3PWsDMGKWDtDQ/Digitizing-the-GES-Curriculum-Figma?node-id=0-1&t=1fnNqqJdv6WRWMXV-1) inside the `frontend`

<img width="505" alt="Screen Shot 2024-08-01 at 4 13 28 PM" src="https://github.com/user-attachments/assets/541861fa-a8a3-4a78-bc14-516d331c0814">

## Tasks

1. **Set up a component to contain the various  sections**

2. **Test the Implementation**
   - Verify that  both sections are responsive across various devices,also ensuring that it matches the figma design.

## Acceptance Criteria
-matches the design
- responsive across various devices

**Comment by JoanaQuadzie** [comment]
I'd to work on this@Emmanuel

**Comment by emmanuelAkpe** [comment]
great. I have assigned to you

**Comment by JoanaQuadzie** [comment]
Noted with thanks
