### ISSUE TITLE
Building the Faq sections of the landing page

### ISSUE THREAD

**Issue by emmanuelAkpe** [mestafrica/digitizing-the-ges-curriculum#14]
## Description
This issue involves building the  sections  in the image below based on the  provided Figma design(https://www.figma.com/design/f6ysqYxUe3PWsDMGKWDtDQ/Digitizing-the-GES-Curriculum-Figma?node-id=0-1&t=1fnNqqJdv6WRWMXV-1) inside the `frontend`

<img width="520" alt="Screen Shot 2024-08-01 at 4 14 02 PM" src="https://github.com/user-attachments/assets/7e2305dd-01c9-442e-be64-07efbfd48e2b">

## Tasks

1. **Set up a component to contain the various  sections**

2. **Test the Implementation**
   - Verify that  both sections are responsive across various devices,also ensuring that it matches the figma design.

## Acceptance Criteria
-matches the design
- responsive across various devices

**Comment by JoanaQuadzie** [comment]
working on this @emmanuelAkpe 
am i using the same image?

**Comment by JoanaQuadzie** [comment]
@emmanuelAkpe this is not closed yet, is there anything to be included?

**Comment by emmanuelAkpe** [comment]
Everything is great @JoanaQuadzie
