### ISSUE TITLE
# Initial Setup for Express and Node.js Backend

### ISSUE THREAD

**Issue by emmanuelAkpe** [mestafrica/digitizing-the-ges-curriculum#2]
## Description

This issue is to set up the initial backend project structure in the `backend` directory using Express and Node.js. This will include initializing the project, installing necessary dependencies, and creating a basic server setup.

## Tasks

1. **Initialize the Project in `backend`:**
   - Navigate to the `backend` directory.
   - Initialize a new Node.js project 

2. **Install Dependencies:**
   - Install Express.js.
   - Install necessary packages as needed (e.g., `dotenv` for environment variables, `mongoose` for MongoDB, etc).

3. **Create Basic Project Structure:**
   - controllers,models,middlewares,utils etc
   - Set up the entry point file (`index.js,app.js`).
   - Create an `.env` file for environment variables.

4. **Set Up Basic Express Server:**
   - Configure the Express server 

5. **Configure Database Connection :**
   - Set up the database connection based on the database you are using ( MongoDB ).
   - Ensure the connection is established correctly

## Acceptance Criteria

- The project should be initialized with Node.js and Express in the `backend` directory.
- A basic Express server should be set up and running.
- Essential dependencies should be installed and configured.
- Optional database connection should be configured if applicable.

## Steps to Reproduce

1. Clone the repository.
2. Navigate to the `backend` directory.
3. Follow the steps to set up the project.
4. Run the server and verify the basic setup.

## Additional Context

- [Express Documentation](https://expressjs.com/en/starter/installing.html)
- [dotenv Documentation](https://www.npmjs.com/package/dotenv)
- [Mongoose Documentation](https://mongoosejs.com/docs/)

**Comment by lyril-sly** [comment]
I am setting up the Project

**Comment by emmanuelAkpe** [comment]
Thank you. Assigned to you @lyril-sly
