### ISSUE TITLE
Create Signup UI 

### ISSUE THREAD

**Issue by emmanuelAkpe** [mestafrica/digitizing-the-ges-curriculum#7]
## Description
This issue involves setting up basic routing, color variables in TailwindCSS, and designing a signup UI based on a provided Figma design(https://www.figma.com/design/f6ysqYxUe3PWsDMGKWDtDQ/Digitizing-the-GES-Curriculum-Figma?node-id=0-1&t=1fnNqqJdv6WRWMXV-1) inside the `frontend`

## Tasks

1. **Set Up Basic Routing- React Router **
   -Homepage
   -Register Page

2. **Configure TailwindCSS**
   - Define color variables based on the design specifications.

3. **Design Signup UI**
   - Create a signup form based on the provided Figma design.
   - Implement form validation and error handling.

4. **Test the Implementation**
   - Verify the signup functionality end-to-end, ensuring that users can sign up successfully.

## Acceptance Criteria
- Basic routing .
- TailwindCSS is configured with appropriate color variables.
- A signup form matching the Figma design is created.
- The signup functionality is tested and verified to be working correctly.

**Comment by iamatinad** [comment]
@emmanuelAkpe please I would like to pick this up
